### PR TITLE
fix(revop): add support for gradless ops

### PR DESCRIPTION
**Pull request by ClashLuke**
### What was the problem?

Some operations, such as sort or argsort appear to have weird gradients in pytorch. Those cause the library to crash, with this error message:
>RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

### How this PR fixes the problem?

This PR introduces an potential problem to fix an active issue. In other words: It allows unused gradients. Nothing else changed.

### Check lists (check `x` in `[ ]` of list items)

- [ ] Test passed (Not tested)
- [ ] Coding style (indentation, etc) (Not tested)

### CODE REVIEW

**Comment by silvandeleemput** [comment]
Hi @ClashLuke, thanks for bringing this issue to our attention. However, I am wondering if it isn't better to add an option (e.g.: grad_allow_unused) to the InvertibleModuleWrapper for toggling the allow_unused attribute to solve this issue instead of permanently setting the allow_unused value to True. Generally, I think that you might want to get notified by having unused gradients in your network, but in some use cases (like yours presumably) this might require setting the attribute. 

Would you be agreeable with such a solution? 

If you can it would also be helpful to provide a (short) code snippet of your issue and the MemCNN, PyTorch, and Python versions, so I can easily reproduce it. That would be super helpful.

**Comment by ClashLuke** [comment]
Apperently it's more of an issue with unused layers in pytorch modules, rather than sorting. Sorry for my false report.\
As discussed above, a flag was added to MemCNNs InvertibleModuleWrapper in the commit above.\


I've tested the code locally with v1.4 and v1.5 of pytorch using 3.7.7 and 3.7.6 anaconda-python respectively. The snipped used can be found below:
```PYTHON
import memcnn
import torch


class Sort(torch.nn.Module):
    def __init__(self, features):
        super().__init__()
        self.linear = torch.nn.Linear(features, features)
        self.linear2 = torch.nn.Linear(features, features)

    def forward(self, fn_input: torch.Tensor) -> torch.Tensor:
        return self.linear(fn_input)


#module = memcnn.InvertibleModuleWrapper(memcnn.AdditiveCoupling(Sort(1)), allow_unused_gradients=True) 
module = memcnn.InvertibleModuleWrapper(memcnn.AdditiveCoupling(Sort(1))) 
tensor = torch.randn((1, 2), requires_grad=True)
output = module(tensor)
output.mean().backward()
```
which, when executed yields the following error message:
>RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

**Comment by silvandeleemput** [comment]
@ClashLuke I see that you have added code related to issue #49 to this PR as well. I would suggest separating issue #49 and this PR (support for gradless ops) into two different PRs, since they are unrelated.

**Comment by silvandeleemput** [comment]
@ClashLuke Thanks for splitting the PRs, I have commented on #50.

Regarding this issue, do you still think this is a useful feature to add the grad_allow_unused argument? I expect that now you know it was due to the unused layer that you could do without this feature (correct me if I am wrong). In my opinion, the solution is solid, however I am concerned that it only covers very rare use cases and bloats the InvertibleModuleWrapper with an additional argument. I am thinking now to shelve this solution and if the issue is ever raised again (and proves to be essential), then I'll reconsider adding it.

**Comment by ClashLuke** [comment]
@silvandeleemput You're right, this certainly is an edge case and bloating the module certainly isn't a good idea. While technically useful, especially with dynamic graph construction, it certainly isn't important enough to be kept inside.\
If the issue is raised again, or the usage of dynamic layer usage becomes a standard, it may be useful to add this option in the future. However, as it's trivial to reimplement, I'd go ahead and close this PR.

**Pull request closed without merging**
